spring.application.name=transacciones-backend
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n

# ===================================================================
# SERVER CONFIGURATION
# ===================================================================
server.port=8080

# ===================================================================
# H2 DATABASE CONFIGURATION (In-Memory para Tests)
# ===================================================================
spring.datasource.url=jdbc:h2:mem:transaccionesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar la consola H2 en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false

# ===================================================================
# JPA / HIBERNATE
# ===================================================================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# IMPORTANTE (Spring Boot 3.x): 
# Asegura que Hibernate genere las tablas ANTES de ejecutar data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# ===================================================================
# LOGGING CONFIGURATION (Requisito Arquitectura)
# ===================================================================
logging.level.root=INFO
# Nivel DEBUG para nuestro paquete para ver detalles internos
logging.level.com.banco.transacciones=DEBUG

# Patron de Log inyectando el MDC (correlationId) requerido por arquitectura
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{correlationId}] %msg%n